version: '3.9'

services:
  flaskapp:
    container_name: flaskapp
    image: flaskapp
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    build: .
    ports:
      - "5000:5000"    
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: conversiontool
      POSTGRES_USER: conversiontool
      POSTGRES_PASSWORD: conversiontool
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}