version: '3.9'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: .
    command: gunicorn --bind 0.0.0.0:80 manage:app
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: conversiontool
      POSTGRES_USER: conversiontool
      POSTGRES_PASSWORD: conversiontool
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}


  version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod: