version: '3.9'

services:
  flaskapp:
    container_name: flaskapp
    image: flaskapp
    command: gunicorn --workers=4 --bind 0.0.0.0:5000 wsgi:app
    build: .
    ports:
      - "5000:5000"    
    environment:
      - DATABASE_URL=postgresql://conversiontool:conversiontool@34.27.234.145:5432/conversiontool
    #depends_on:
    #  - db
    
  #db:
  #  container_name: db
  #  image: postgres:alpine
  #  ports:
  #    - "5432:5432"
  #  environment:
  #    POSTGRES_DB: conversiontool
  #    POSTGRES_USER: conversiontool
  #    POSTGRES_PASSWORD: conversiontool
  #  volumes:
  #    - pgdata:/var/lib/postgresql/data


#volumes:
#  pgdata: {}