version: '3.9'

services:
  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: conversiontool
      POSTGRES_USER: conversiontool
      POSTGRES_PASSWORD: conversiontool
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}