service: worker-app

runtime: custom

runtime_config:
  python_version: 3

env: flex

entrypoint: gunicorn -b :5000 main:app

#manual_scaling:
#  instances: 1
#resources:
#  cpu: 1
#  memory_gb: 0.5
#  disk_size_gb: 10